extension_dir = "ext"
upload_max_filesize = 5M
post_max_size = 8M
upload_tmp_dir = "E:/Documents/Llander/Yuemnigga/IT12/Mommas-Bakeshop/storage/tmp"
sys_temp_dir = "E:/Documents/Llander/Yuemnigga/IT12/Mommas-Bakeshop/storage/tmp"

; Database Drivers
extension=pdo_mysql
extension=mysqli

; String Handling (Fixes the current error)
extension=mbstring

; General Compatibility (Prevents future errors)
extension=openssl
extension=curl
extension=fileinfo

; Performance & Compatibility (Fixes ASLR error on Windows)
opcache.enable=0
opcache.enable_cli=0
opcache.file_cache_fallback=1
opcache.file_cache=storage/framework/cache/opcache
opcache.jit=off
opcache.jit=off
