<?php

return [
    'tracked_tables' => [
        'roles',
        'users',
        'customers',
        'permission_groups',
        'permissions',
        'role_preset_permissions',
        'permissions_set',
        'categories',
        'products',
        'production_batch_details',
        'production_batches',
        'product_leftover_snapshots',
        'product_leftovers',
        'sales',
        'payments',
        'partial_payments',
        'sold_products',
        'custom_order_details',
        'custom_orders',
        'shrinkages',
        'shrinked_products',
        'inventory',
        'stock_in_details',
        'stock_ins',
        'stock_out_details',
        'stock_outs',
        'inventory_leftover_snapshots',
        'inventory_leftovers',
    ],
    'snapshot_directory' => 'backups/snapshots',
    'incremental_directory' => 'backups/incrementals',
    'lock_name' => 'mommas_bakeshop_database_backups',
    'lock_timeout_seconds' => 15,
];
